# Markdownlint Configuration for Proxmox Homelab
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD003 - Heading style
MD003:
  style: atx

# MD004 - Unordered list style
MD004:
  style: dash

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD009 - Trailing spaces (allow 2 for line break)
MD009:
  br_spaces: 2

# MD010 - Hard tabs
MD010:
  code_blocks: false

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013 - Line length
MD013:
  line_length: 200
  heading_line_length: 120
  code_block_line_length: 200
  code_blocks: false
  tables: false

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!"

# MD029 - Ordered list item prefix
MD029:
  style: ordered

# MD033 - Inline HTML (allow for README badges, diagrams, etc.)
MD033:
  allowed_elements:
    - br
    - img
    - a
    - details
    - summary
    - sup
    - sub

# MD034 - Bare URLs
MD034: false

# MD036 - Emphasis used instead of heading
MD036: false

# MD041 - First line in file should be a top level heading
MD041: true

# MD046 - Code block style
MD046:
  style: fenced

# MD048 - Code fence style
MD048:
  style: backtick

# MD049 - Emphasis style
MD049:
  style: asterisk

# MD050 - Strong style
MD050:
  style: asterisk
